Added title to the home page and made it responsive
J0SAL/Decentralized-Expense-Tracker pull request #105
Opened 2023-06-14 16:17 UTC by ojasaklechayt

Issue Number: #49 

Description:
      I have done the following things:
        1. Added H1 tag which says " Welcome to Jarvis " which improves the UI
        2. Made it basic responsive
 
Screenshot: 
![image](https://github.com/J0SAL/Decentralized-Expense-Tracker/assets/90605717/b6e06678-0cbe-47c8-b506-9c0c7f3d79ad)

2023-06-16 20:24 UTC, J0SAL commented
@ojasaklechayt, it's failing due to some reason, please resolve that.
I had already told you the trick to check the failing conditions.

2023-06-17 13:59 UTC, ojasaklechayt commented
> @ojasaklechayt, it's failing due to some reason, please resolve that. I had already told you the trick to check the failing conditions.

I did npm run build but it was going correct

2023-06-20 19:22 UTC, ojasaklechayt commented
@J0SAL

2023-06-21 17:57 UTC, J0SAL requested changes
There are a lot of problems with the PR, I have either requested changes or marked with the *??*

few problems are, 
- code is not sync
- the whole file shouldn't be changed in case if just a line is changed
- don't make indentation changes to the files

To resolve these issues, my advice would be to create a new PR(with a new fork/updated code) and make specific changes...
you can ask @Abhijit25Mishra for help

2023-06-21 17:57 UTC, J0SAL commented on frontend/components/transactions/DownloadTransactions.tsx
> +import { Button } from "react-bootstrap";
??

2023-06-21 17:57 UTC, J0SAL commented on frontend/next.config.js
> +module.exports = nextConfig
undo these

2023-06-21 17:57 UTC, J0SAL commented on frontend/pages/_app.tsx
> +}
what's the change here?

2023-06-21 17:57 UTC, J0SAL commented on frontend/pages/api/hello.ts
> +}
undo these

2023-06-21 17:57 UTC, J0SAL commented on frontend/pages/index.tsx
> +}
??

2023-06-21 17:57 UTC, J0SAL commented on frontend/styles/Home.module.css
> +}
??

2023-06-21 17:57 UTC, J0SAL commented on frontend/styles/globals.css
>  }
??

2023-06-22 12:42 UTC, ojasaklechayt commented
All these are due to the conflicts as soon as I merge these. Some other sync appears which cause the merge conflicts

2023-06-23 10:45 UTC, J0SAL commented
> There are a lot of problems with the PR, I have either requested changes or marked with the _??_
> 
> few problems are,
> 
> * code is not sync
> * the whole file shouldn't be changed in case if just a line is changed
> * don't make indentation changes to the files
> 
> To resolve these issues, my advice would be to create a new PR(with a new fork/updated code) and make specific changes... you can ask @Abhijit25Mishra for help

Like I said here, your changes are undoing the previously updated changes, and there are really many unwanted changes... best thing would be to create a new PR, which will work on the code from the most recent main branch

2023-06-23 16:03 UTC, ojasaklechayt commented
> > There are a lot of problems with the PR, I have either requested changes or marked with the _??_
> > few problems are,
> > 
> > * code is not sync
> > * the whole file shouldn't be changed in case if just a line is changed
> > * don't make indentation changes to the files
> > 
> > To resolve these issues, my advice would be to create a new PR(with a new fork/updated code) and make specific changes... you can ask @Abhijit25Mishra for help
> 
> Like I said here, your changes are undoing the previously updated changes, and there are really many unwanted changes... best thing would be to create a new PR, which will work on the code from the most recent main branch

okay

2023-06-23 16:03 UTC, closed without merging