Lazy loading is added
J0SAL/Decentralized-Expense-Tracker pull request #126
Opened 2023-07-01 07:07 UTC by shraddha761

Resolves #123 

## Description

Add lazy loading to overview, Transactions, PerformanceGraph , Performers 

## Screenshots

## Checklist 

- [x] My code adheres to the established style guidelines of the project.
- [x] I have included comments in areas that may be difficult to understand.
- [x] My changes have not introduced any new warnings.
- [x] I have conducted a self-review of my code.

2023-07-01 08:16 UTC, J0SAL commented
@Abhijit25Mishra can you review this

2023-07-03 09:22 UTC, shraddha761 commented
@J0SAL please review my pr

2023-07-03 14:27 UTC, J0SAL commented
> @J0SAL please review my pr

Let's wait for @Abhijit25Mishra to review it

2023-07-04 04:57 UTC, Abhijit25Mishra requested changes

2023-07-04 04:57 UTC, Abhijit25Mishra commented on frontend/pages/_app.tsx
> +                <PageNavbar />
Please note that these type of changes do not get commited. For people for review and merge your code have to spend time and make sure this is correct. 

simply put, if you make our job easier the fast things get processed.

2023-07-04 04:57 UTC, Abhijit25Mishra commented on frontend/pages/_app.tsx
> +}
same problem over here, how did this even get commited ?

2023-07-04 04:57 UTC, Abhijit25Mishra commented on frontend/pages/_app.tsx
> +import React from "react";
details like this (implementation specification) go to the description. Why have you changed this import from line 6 to line 12 ?

2023-07-04 05:18 UTC, shraddha761 commented
@Abhijit25Mishra apologize for all this mistake I'll make fresh pr and implement lazy loading properly

2023-07-04 13:57 UTC, closed without merging