Create Dependabot.yaml
J0SAL/Decentralized-Expense-Tracker pull request #99
Opened 2023-06-04 16:42 UTC by Tushar98644

@J0SAL pls review

2023-06-08 18:50 UTC, Abhijit25Mishra commented
Sure

2023-06-11 18:24 UTC, Abhijit25Mishra commented
Make your PR title specific (if possible)
    Update your PR template like this:

    Fixes: https://github.com/J0SAL/Decentralized-Expense-Tracker/pull/99
    Description:
    Attach Screenshots (if needed)

2023-06-11 18:26 UTC, Abhijit25Mishra approved these changes
Code seems fine.

2023-06-13 08:48 UTC, J0SAL requested changes

2023-07-11 05:30 UTC, closed without merging